
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import React from 'react';
import {Button, ButtonGroup} from "@nextui-org/button";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Colégio Tableau Jundiai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Image
            src="/tableauAzul.png"
            width={100}
            height={80}
            alt="logotipo colegio tableau"
            className="log_tableauMobile"

            />
        <nav className="navbar">
          
            <Image
            src="/logotableau.png"
            width={100}
            height={80}
            alt="logotipo colegio tableau"
            className="log_tableau"

            />
            <div className="flex flex-wrap gap-5  btn">
            
            <Link href="/tecnico">
            <Button color="primary">
                Cursos Técnico
            </Button>
            
            </Link>

            <Button color="primary">
                Ensino Fundamental e Médio
            </Button>
            </div>
            
          
          
        

          <Image
            src="/mackNegativor.png"
            width={200}
            height={80}
            alt="logotipo mackenzie"
            className="log_mack"
          />
          
           

          

        </nav>
        {children}
      </body>
    </html>
  );
}
